# Generated by Django 5.0.3 on 2026-06-15 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('extracted_links', models.JSONField(blank=True, default=list, help_text='List of {"url": str, "title": str} extracted from the page for navigation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_entries', to='tenant_manager.tenant')),
            ],
            options={
                'db_table': 'knowledge_base_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='Route path, e.g. /about, /dashboard/students', max_length=500)),
                ('name', models.CharField(help_text='Human-readable name, e.g. About Us', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='What this page does, for chatbot context')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='List of role names allowed to access this route, e.g. ["admin", "student"]')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_entries', to='tenant_manager.tenant')),
            ],
            options={
                'db_table': 'route_entry',
                'ordering': ['sort_order', 'path'],
            },
        ),
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Role identifier, e.g. admin, student, trainer', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable role name, e.g. Organization Admin', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Description of what this role can do, for chatbot context')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='tenant_manager.tenant')),
            ],
            options={
                'db_table': 'role_config',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
