# Generated by Django 5.0.3 on 2026-06-15 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_proxy', '0001_initial'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neo4jConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(blank=True, default='', max_length=500)),
                ('username', models.CharField(blank=True, default='neo4j', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=500)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neo4j_config', to='tenant_manager.tenant')),
            ],
            options={
                'db_table': 'neo4j_config',
            },
        ),
    ]
