# Generated by Django 5.0.3 on 2026-06-15 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(default='guest', max_length=100)),
                ('current_route', models.CharField(blank=True, default='', max_length=500)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('upstream_latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='tenant_manager.tenant')),
            ],
            options={
                'db_table': 'message_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='message_log_tenant__0bf9b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to='tenant_manager.tenant')),
            ],
            options={
                'db_table': 'usage_summary',
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
    ]
