# Generated by Django 5.0.3 on 2026-06-15 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization/tenant name', max_length=200)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('monthly_message_quota', models.IntegerField(default=500, help_text='Maximum messages allowed per month')),
                ('allowed_origins', models.TextField(blank=True, default='', help_text='Newline-separated list of allowed CORS origins')),
                ('custom_system_prompt_override', models.TextField(blank=True, default='', help_text='Optional custom system prompt for the AI')),
                ('neo4j_uri', models.CharField(blank=True, default='', max_length=500)),
                ('neo4j_user', models.CharField(blank=True, default='', max_length=100)),
                ('neo4j_password', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw API key', max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='Display prefix like dlk_8408_', max_length=20)),
                ('name', models.CharField(help_text='Human-readable name for this key', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_origins', models.TextField(blank=True, default='', help_text='Newline-separated CORS origins override for this key')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenant_manager.tenant')),
            ],
            options={
                'db_table': 'api_key',
                'ordering': ['-created_at'],
            },
        ),
    ]
